[build]
  command = "npm run build"
  publish = "_site"
  edge_functions = "netlify/edge-functions"   # <-- mueve aquí el directorio

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# ==== Functions (Node) ====
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."submission-created"]
  external_node_modules = ["nodemailer"]

# ==== Redirects bonitos ====
[[redirects]]
  from = "/privacidad.html"
  to = "/privacidad/"
  status = 301

[[redirects]]
  from = "/legal.html"
  to = "/legal/"
  status = 301

[[redirects]]
  from = "/cookies.html"
  to = "/cookies/"
  status = 301

# ==== Edge Functions ====
[[edge_functions]]
  path = "/*"
  function = "i18n"
