# ============================
# Netlify config (Casa Bardena Negra)
# ============================

[build]
  command = "npm run build"
  publish = "_site"
  edge_functions = "netlify/edge-functions"   # directorio de Edge Functions

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund --loglevel=error"

# ==== Functions (Node) ====
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# ejemplo: función que envía emails
[functions."submission-created"]
  external_node_modules = ["nodemailer"]

# ============================
# Headers (seguridad + caché)
# ============================

# Seguridad base en todo el sitio
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-control = "public, max-age=0, must-revalidate"

# Caché largo para assets versionados
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Caché largo para imágenes
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tipos útiles
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

# Forzar https y sin www
[[redirects]]
  from = "http://bardenanegra.es/*"
  to = "https://bardenanegra.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bardenanegra.es/*"
  to = "https://bardenanegra.es/:splat"
  status = 301
  force = true

# ============================
# Redirects bonitos / canonicals
# ============================
# --- NO tocar /reports/*.html (informes Lighthouse) ---
[[redirects]]
  from = "/reports/:file.html"
  to   = "/reports/:file.html"
  status = 200
  force = true

# /index.html → /
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Páginas “.html” que te interese canonizar (solo si existen legacy enlaces)
[[redirects]]
  from = "/privacidad.html"
  to   = "/privacidad/"
  status = 301

[[redirects]]
  from = "/legal.html"
  to   = "/legal/"
  status = 301

[[redirects]]
  from = "/cookies.html"
  to   = "/cookies/"
  status = 301

[[redirects]]
  from = "/reservas.html"
  to   = "/reservas/"
  status = 301

[[redirects]]
  from = "/la-casa.html"
  to   = "/la-casa/"
  status = 301

[[redirects]]
  from = "/entorno.html"
  to   = "/entorno/"
  status = 301

[[redirects]]
  from = "/la-casa/galeria.html"
  to   = "/la-casa/galeria/"
  status = 301

[[redirects]]
  from = "/la-casa/equipamiento.html"
  to   = "/la-casa/equipamiento/"
  status = 301

[[redirects]]
  from = "/la-casa/faq.html"
  to   = "/la-casa/faq/"
  status = 301

[[redirects]]
  from = "/entorno/tudela.html"
  to   = "/entorno/tudela/"
  status = 301

[[redirects]]
  from = "/entorno/sendaviva.html"
  to   = "/entorno/sendaviva/"
  status = 301

[[redirects]]
  from = "/entorno/bardenas.html"
  to   = "/entorno/bardenas/"
  status = 301

# ============================
# Edge Functions (i18n, etc.)
# ============================

# Ejecuta la Edge Function "i18n" en todo el sitio
[[edge_functions]]
  path = "/*"
  function = "i18n"
# (Si más adelante quieres evitar que corra en /assets/ o /images/, podemos
#  afinar el patrón de rutas; ver docs de declaraciones de Edge Functions.)  # :contentReference[oaicite:1]{index=1}

# ============================
# Lighthouse plugin (auditoría)
# ============================

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    locale = "es"
    # preset = "desktop"   # opcional: auditar como escritorio (por defecto: móvil)

  # [plugins.inputs.thresholds]
    # performance = 0.80
    # accessibility = 0.90
    # seo = 0.90

  # — Básicas —
  [[plugins.inputs.audits]]
    path = "/"
    output_path = "reports/lh-home.html"

  [[plugins.inputs.audits]]
    path = "/la-casa/"
    output_path = "reports/lh-la-casa.html"

  [[plugins.inputs.audits]]
    path = "/entorno/"
    output_path = "reports/lh-entorno.html"

  [[plugins.inputs.audits]]
    path = "/reservas/"
    output_path = "reports/lh-reservas.html"

  # — Subpáginas de Entorno (borra las que no existan) —
  [[plugins.inputs.audits]]
    path = "/entorno/tudela/"
    output_path = "reports/lh-entorno-tudela.html"

  [[plugins.inputs.audits]]
    path = "/entorno/sendaviva/"
    output_path = "reports/lh-entorno-sendaviva.html"

  [[plugins.inputs.audits]]
    path = "/entorno/bardenas/"
    output_path = "reports/lh-entorno-bardenas.html"

  # — Legales (opcionales) —
  [[plugins.inputs.audits]]
    path = "/legal/"
    output_path = "reports/lh-legal.html"

  [[plugins.inputs.audits]]
    path = "/privacidad/"
    output_path = "reports/lh-privacidad.html"

  [[plugins.inputs.audits]]
    path = "/cookies/"
    output_path = "reports/lh-cookies.html"
